apiVersion: apps/v1 
kind: Deployment 
metadata: 
  name: spring-app-k8s 
spec: 
  template: 
    metadata: 
      name: spring-app-pod 
      labels:
        app: spring-app  
    spec: 
      containers:
      - name: spring-app 
        image: zeenia/spring-app 
        ports: 
        - containerPort: 8085
        env: 
        - name: "MYSQL_ROOT_USER"
          value: root
          name: "MYSQL_ROOT_PASSWORD"
          value: Chris93!
          name: "DB_HOST"
          value: bitnamisql-mysql.default.svc.cluster.local:3306
          name: "DB_NAME"
          value: springdb
  replicas: 1 
  selector: 
    matchLabels: 
      app: spring-app 

---
apiVersion: v1
kind: Service
metadata:
  name: spring-app-service
spec:
  type: NodePort
  ports:
    - protocol: "TCP"
      targetPort: 8085
      port: 8085
  selector:
    app: spring-app
