apiVersion: apps/v1 
kind: Deployment 
metadata: 
  name: spring-app-k8s 
spec: 
  template: 
    metadata: 
      name: spring-app-pod 
      labels:
        app: spring-app  
    spec: 
      containers:
      - name: spring-app 
        image: zeenia/spring-app 
        ports: 
        - containerPort: 8080
        env: 
        - name: "MYSQL_ROOT_USER"
          value: "root"
          name: "MYSQL_ROOT_PASSWORD"
          value: "fQq0E5MWfR"
          name: "MYSQL_DATABASE_URL"
          value: "jdbc:mysql://10.107.196.89:3306/springdb?serverTimezone=UTC&useLegacyDatetimeCode=false"
  replicas: 1 
  selector: 
    matchLabels: 
      app: spring-app 
  
