apiVersion: apps/v1 
kind: Deployment 
metadata: 
  name: spring-app-k8s 
spec: 
  template: 
    metadata: 
      name: spring-app-pod 
      labels:
        app: spring-app  
    spec: 
      containers:
      - name: spring-app 
        image: zeenia/spring-app 
        ports: 
        - containerPort: 8080
        env: 
        - name: "MYSQL_ROOT_USER"
          value: "root"
          name: "MYSQL_ROOT_PASSWORD"
          value: "fQq0E5MWfR"
          name: "MYSQL_DATABASE_URL"
          value: "jdbc:mysql://bitnamisql-mysql.spring.svc.cluster.local:3306/springdb"
  replicas: 1 
  selector: 
    matchLabels: 
      app: spring-app 

---
apiVersion: v1
kind: Service
metadata:
  name: spring-app-service
spec:
  type: LoadBalancer
  ports:
    - protocol: TCP
      targetPort: 8080
      port: 80
  selector:
    app: spring-app
