apiVersion: v1 
kind: Service 
metadata:
  name: spring-app-service 
spec: 
  type: LoadBalancer
  ports: 
    - protocol: TCP
      targetPort: 8080 
      port: 80 
  selector: 
    app: spring-app 
